_SUPPORTED = not host_info().os.is_windows

# buildifier: disable=no-effect
ocaml_binary(
    name = "test-unix",
    srcs = ["test_unix.ml"],
    deps = ["root//third-party/ocaml:unix"],
) if _SUPPORTED else None
