name: use pre-existing switch
on:
  push:
  pull_request:
  workflow_dispatch:
jobs:
  run-tests:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu, macos]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'
      - uses: facebook/install-dotslash@latest
      - run: sudo apt-get install opam
        if: matrix.os == 'ubuntu'
      - run: brew install opam coreutils # for realpath
        if: matrix.os == 'macos'
      - run: |-
          opam init --color=always --compiler=5.2.0~beta2 --disable-sandboxing -y
          opam install --color=always ocamlfind
          opam env | sed -e "s/ export .*//g" -e "s/'//g" -e "s/\;//g" >> $GITHUB_ENV
      - run: |-
          mkdir -p third-party/ocaml
          (cd third-party/ocaml && ln -s "$OPAM_SWITCH_PREFIX" opam)
          python3 dromedary.py -s "$(basename $OPAM_SWITCH_PREFIX)" -o third-party/ocaml/BUCK.test
      - run: echo "PATH=$(pwd):$PATH" >> $GITHUB_ENV
      - run: buck2 run root//test:version
      - run: cat $(buck2 build root//test:config --show-full-simple-output)
      - run: buck2 run root//test:str
      - run: buck2 run root//test:unix
